#!/bin/bash
PID_FILE=/var/run/redbubble_workers/newrelic-rabbitmq-agent.pid

case $1 in
  start)
     echo $$ > $PID_FILE;
     cd "$( dirname "${BASH_SOURCE[0]}" )"
     exec /usr/bin/env ruby newrelic_rabbitmq_agent.rb
     ;;
   stop)
     kill `cat $PID_FILE` ;;
   *)
     echo "usage: newrelic-rabbitmq-agent {start|stop}" ;;
esac
exit 0
